apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: DemoApp
  template:
    metadata:
      labels:
        app: DemoApp
    spec:
      containers:
        - name: hello-app-container
          image: 745392035468.dkr.ecr.ap-south-1.amazonaws.com/awskeksdemo:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80